### ISSUE TITLE
Determine Heroku release pipeline

### ISSUE THREAD

**Issue by noragharris** [madeintandem/staffing-strategy#21]
Current release is through Heroku feature and Promote button. However, promote button is copying over env args from staging to production.

https://devcenter.heroku.com/articles/release-phase#design-considerations
https://stackoverflow.com/questions/45064842/heroku-pipeline-staging-env-variable-carried-into-production

**Comment by cainwatson** [comment]
I played around with heroku pipelines on the weekend and I believe if we remove the `REACT_APP_SERVER_API_URL` variable on the frontend, the current setup will work.
